import sys
import subprocess
import os
import shutil
import numpy as np
import soundfile as sf
import librosa
from pathlib import Path

# --- Import local utils ---
import custom_fft
import equalizer_core

# --- CONFIGURATION ---
OUTPUT_FOLDER = r'separated_results'
MODEL_NAME = "htdemucs"
CHUNK_SIZE = 16384 # Process audio in chunks to prevent recursion depth errors in custom_fft

def separate_audio(input_filename):
    """Runs Demucs to separate the input file."""
    input_path = Path(input_filename)
    if not input_path.exists():
        print(f"ERROR: The file '{input_filename}' was not found.")
        return None

    print(f"--- Starting Demucs Separation for: {input_filename} ---")
    
    # Construct the command
    cmd = [
        sys.executable, "-m", "demucs.separate",
        "-n", MODEL_NAME,
        "--out", OUTPUT_FOLDER,
        str(input_path)
    ]
    
    # Force soundfile backend
    env = os.environ.copy()
    env["TORCHAUDIO_BACKEND"] = "soundfile" 

    try:
        subprocess.run(cmd, check=True, env=env)
        print("SUCCESS! Separation complete.")
        
        # Return path to the stems directory
        # Demucs structure: output_folder / model_name / file_name / stems
        return Path(OUTPUT_FOLDER) / MODEL_NAME / input_path.stem
        
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Demucs failed to run. {e}")
        return None

def process_and_recombine(stems_path, user_scales, output_filename="output.wav"):
    """
    Loads stems, applies FFT -> EQ (Scaling) -> IFFT logic, and sums them.
    """
    print("\n--- Starting Recombination with Custom DSP ---")
    
    final_mixture = None
    Fs = None # Sampling rate
    
    # Map friendly names to actual filenames generated by Demucs
    stem_files = {
        'vocals': stems_path / 'vocals.wav',
        'drums': stems_path / 'drums.wav',
        'bass': stems_path / 'bass.wav',
        'other': stems_path / 'other.wav'
    }

    for stem_name, stem_path in stem_files.items():
        if not stem_path.exists():
            continue
            
        print(f"Processing {stem_name}...")
        
        # 1. Load Source Audio (Mono for simplicity in FFT)
        source_time_series, sr = librosa.load(str(stem_path), sr=None, mono=True)
        Fs = sr
        
        # 2. Prepare for chunk processing
        # Because custom_fft is recursive, we must process large files in chunks
        total_samples = len(source_time_series)
        processed_audio = np.zeros_like(source_time_series)
        
        # Define the EQ scheme: One giant band from 0 to Nyquist with the user's scale
        eq_scheme = [{
            'freq_start_hz': 0,
            'freq_end_hz': Fs / 2, # Nyquist
            'scale_value': user_scales.get(stem_name, 1.0)
        }]

        # 3. Process in Chunks
        for i in range(0, total_samples, CHUNK_SIZE):
            chunk = source_time_series[i : i + CHUNK_SIZE]
            
            # FFT (Custom)
            # Note: custom_fft handles padding internally if chunk size isn't power of 2
            fft_data = custom_fft.custom_fft(chunk)
            
            # Apply EQ (Scaling)
            # We map our simple structure to the one equalizer_core expects
            mapped_scheme = []
            for band in eq_scheme:
                mapped_scheme.append({
                    'freq_start_hz': band['freq_start_hz'],
                    'freq_end_hz': band['freq_end_hz'],
                    'scale_factor': band['scale_value']
                })
            
            scaled_fft = equalizer_core.apply_equalization(fft_data, Fs, mapped_scheme)
            
            # IFFT (Custom)
            time_domain_chunk = custom_fft.custom_ifft(scaled_fft).real
            
            # Trim padding if custom_fft added it
            original_len = len(chunk)
            processed_audio[i : i + original_len] = time_domain_chunk[:original_len]

        # 4. Add to final mixture
        if final_mixture is None:
            final_mixture = processed_audio
        else:
            # Ensure lengths match (just in case)
            min_len = min(len(final_mixture), len(processed_audio))
            final_mixture[:min_len] += processed_audio[:min_len]
            
    # 5. Normalize
    if final_mixture is not None:
        max_val = np.max(np.abs(final_mixture))
        if max_val > 1.0:
            final_mixture /= max_val
            print("Output normalized to prevent clipping.")

        # 6. Save
        sf.write(output_filename, final_mixture, Fs)
        print(f"\nDone! Saved mixed file to: {output_filename}")
    else:
        print("Error: No audio processed.")

def main():
    # 1. Get Input File
    input_file = input("Enter the path to your .wav file: ").strip().strip('"')
    
    # 2. Run Separation
    stems_path = separate_audio(input_file)
    
    if not stems_path:
        return

    # 3. Get User Scales
    print("\n--- Enter Scale Values (0.0 to 10.0) ---")
    try:
        scales = {}
        scales['bass'] = float(input("Scale value for Bass (e.g., 1.5): "))
        scales['drums'] = float(input("Scale value for Drums (e.g., 1.0): "))
        scales['vocals'] = float(input("Scale value for Vocals (e.g., 0.0 to mute): "))
        scales['other'] = float(input("Scale value for Others (e.g., 1.0): "))
    except ValueError:
        print("Invalid number entered. Using defaults (1.0).")
        scales = {'bass': 1.0, 'drums': 1.0, 'vocals': 1.0, 'other': 1.0}

    # 4. Process
    process_and_recombine(stems_path, scales)

if __name__ == "__main__":
    main()